/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : AssignmentId,
  'title' : string,
  'dueDate' : Timestamp,
  'description' : string,
  'teacherId' : UserId,
  'uploadedAt' : Timestamp,
  'fileKey' : ExternalBlob,
}
export type AssignmentId = bigint;
export interface AssignmentInput {
  'title' : string,
  'dueDate' : Timestamp,
  'description' : string,
  'fileKey' : ExternalBlob,
}
export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'studentId' : UserId,
  'qrToken' : string,
  'timestamp' : Timestamp,
  'sessionId' : SessionId,
}
export interface AttendanceStats {
  'studentId' : UserId,
  'totalPeriods' : bigint,
  'attendedPeriods' : bigint,
  'percentage' : number,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null };
export type ExternalBlob = Uint8Array;
export interface QrSession {
  'token' : string,
  'expiresAt' : Timestamp,
  'createdAt' : Timestamp,
  'teacherId' : UserId,
  'sessionId' : SessionId,
  'courseName' : string,
}
export type SessionId = string;
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'principal' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'teacher' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createAssignment' : ActorMethod<[AssignmentInput], Assignment>,
  'createQrSession' : ActorMethod<[string], QrSession>,
  'deleteAssignment' : ActorMethod<[AssignmentId], boolean>,
  'getActiveQrSession' : ActorMethod<[], [] | [QrSession]>,
  'getAllStudentAttendanceStats' : ActorMethod<[], Array<AttendanceStats>>,
  'getAssignment' : ActorMethod<[AssignmentId], [] | [Assignment]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getMyAttendanceStats' : ActorMethod<[], AttendanceStats>,
  'getSessionAttendance' : ActorMethod<[SessionId], Array<AttendanceRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'listAssignments' : ActorMethod<[], Array<Assignment>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAttendance' : ActorMethod<[SessionId, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];