/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AssignmentInput = IDL.Record({
  'title' : IDL.Text,
  'dueDate' : Timestamp,
  'description' : IDL.Text,
  'fileKey' : ExternalBlob,
});
export const AssignmentId = IDL.Nat;
export const UserId = IDL.Principal;
export const Assignment = IDL.Record({
  'id' : AssignmentId,
  'title' : IDL.Text,
  'dueDate' : Timestamp,
  'description' : IDL.Text,
  'teacherId' : UserId,
  'uploadedAt' : Timestamp,
  'fileKey' : ExternalBlob,
});
export const SessionId = IDL.Text;
export const QrSession = IDL.Record({
  'token' : IDL.Text,
  'expiresAt' : Timestamp,
  'createdAt' : Timestamp,
  'teacherId' : UserId,
  'sessionId' : SessionId,
  'courseName' : IDL.Text,
});
export const AttendanceStats = IDL.Record({
  'studentId' : UserId,
  'totalPeriods' : IDL.Nat,
  'attendedPeriods' : IDL.Nat,
  'percentage' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'teacher' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'studentId' : UserId,
  'qrToken' : IDL.Text,
  'timestamp' : Timestamp,
  'sessionId' : SessionId,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createAssignment' : IDL.Func([AssignmentInput], [Assignment], []),
  'createQrSession' : IDL.Func([IDL.Text], [QrSession], []),
  'deleteAssignment' : IDL.Func([AssignmentId], [IDL.Bool], []),
  'getActiveQrSession' : IDL.Func([], [IDL.Opt(QrSession)], ['query']),
  'getAllStudentAttendanceStats' : IDL.Func(
      [],
      [IDL.Vec(AttendanceStats)],
      ['query'],
    ),
  'getAssignment' : IDL.Func([AssignmentId], [IDL.Opt(Assignment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMyAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getMyAttendanceStats' : IDL.Func([], [AttendanceStats], ['query']),
  'getSessionAttendance' : IDL.Func(
      [SessionId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAttendance' : IDL.Func([SessionId, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AssignmentInput = IDL.Record({
    'title' : IDL.Text,
    'dueDate' : Timestamp,
    'description' : IDL.Text,
    'fileKey' : ExternalBlob,
  });
  const AssignmentId = IDL.Nat;
  const UserId = IDL.Principal;
  const Assignment = IDL.Record({
    'id' : AssignmentId,
    'title' : IDL.Text,
    'dueDate' : Timestamp,
    'description' : IDL.Text,
    'teacherId' : UserId,
    'uploadedAt' : Timestamp,
    'fileKey' : ExternalBlob,
  });
  const SessionId = IDL.Text;
  const QrSession = IDL.Record({
    'token' : IDL.Text,
    'expiresAt' : Timestamp,
    'createdAt' : Timestamp,
    'teacherId' : UserId,
    'sessionId' : SessionId,
    'courseName' : IDL.Text,
  });
  const AttendanceStats = IDL.Record({
    'studentId' : UserId,
    'totalPeriods' : IDL.Nat,
    'attendedPeriods' : IDL.Nat,
    'percentage' : IDL.Float64,
  });
  const UserRole = IDL.Variant({ 'teacher' : IDL.Null, 'student' : IDL.Null });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'studentId' : UserId,
    'qrToken' : IDL.Text,
    'timestamp' : Timestamp,
    'sessionId' : SessionId,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createAssignment' : IDL.Func([AssignmentInput], [Assignment], []),
    'createQrSession' : IDL.Func([IDL.Text], [QrSession], []),
    'deleteAssignment' : IDL.Func([AssignmentId], [IDL.Bool], []),
    'getActiveQrSession' : IDL.Func([], [IDL.Opt(QrSession)], ['query']),
    'getAllStudentAttendanceStats' : IDL.Func(
        [],
        [IDL.Vec(AttendanceStats)],
        ['query'],
      ),
    'getAssignment' : IDL.Func(
        [AssignmentId],
        [IDL.Opt(Assignment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMyAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getMyAttendanceStats' : IDL.Func([], [AttendanceStats], ['query']),
    'getSessionAttendance' : IDL.Func(
        [SessionId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'listAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAttendance' : IDL.Func([SessionId, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };